apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-deployment
  name: petclinic-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: doongu/petclinic-spring:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: log-volume
          mountPath: /doongu/logs
      volumes:
      - name: log-volume
        hostPath:
          type: Directory
          path: /logs
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

